version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  test:
    build: .
    command: sh -c "python formmatcher/forms/tests/test_get.py"
    volumes:
      - .:/app
    depends_on:
      - web
